googleAnalytics = "G-T0F37H2CM6"
# robots.txt
enableRobotsTXT = true
paginate = 100
summaryLength = 30

buildDrafts = false
buildFuture = false
# sitemap 생성
[sitemap]
  changefreq = "daily"
  filename = "sitemap.xml"
  priority = 0.5

[related]
  threshold = 0
  toLower = false

    [[related.indices]]
        name = "tags"
        weight = 100

    [[related.indices]]
        name = "categories"
        weight = 100

    [[related.indices]]
        name = "series"
        weight = 50

    [[related.indices]]
        name = "authors"
        weight = 20

    [[related.indices]]
        name = "date"
        weight = 10

    [[related.indices]]
      applyFilter = false
      name = 'fragmentrefs'
      type = 'fragments'
      weight = 10


[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"
[outputs]
  home = ["HTML", "RSS", "JSON"]
